Made tav-copy-simulations similar to the other two tav-copy scripts

diff --git a/bin/tav-copy-simulations b/bin/tav-copy-simulations
--- a/bin/tav-copy-simulations
+++ b/bin/tav-copy-simulations
@@ -1,5 +1,6 @@
 #!/bin/bash
-# Copy benchmark FEA and/or CFD results to the user's bumper/results directory.
+# Copy TAVIguide FEA or CFD simulation results.
+# v1.0
 
 # Functions
 
@@ -7,122 +8,105 @@
 usage() {
     cat <<EOF
 
-Usage: $(basename $0) [options] BENCHID
+Usage: $(basename $0) [options] TASK SRCID TGTID
 
-Copy FEA and/or CFD simulation results of benchmark case BENCHID to the user's
-bumper/results directory. Optionally rename the copied files and/or create
-accompanying .done files in the user's bumper/requests directory.
+Copy the simulation result files necessary for finishing TASK of case TGTID
+(which is an instance of source case SRCID) in TAVIguide-web. TASK can be one
+of 'fea' or 'cfd'.
 
 Options:
+
   -n : Dry run. Only show what would happen, but don't actually do anything.
-  -d : Create a .done file in the user's bumper/request directory for each
-       simulation that was copied. When done as user 'myfeops' on 'feops1',
-       the presence of the .done files notifies TAVIguide-web that the
-       respective simulations have finished.
-  -f : Copy the chosen benchmark case's FEA results.
-  -c : Copy the chosen benchmark case's CFD results.
-  -l : List the available benchmark cases in BENCHROOT and exit.
-  -r NEWID : When given, all copied files are renamed to have BENCHID replaced
-             with NEWID.
-  -b BENCHROOT : Specify the root directory of the benchmark cases.
-        The default benchmark case root directory is:
-          - '/srv/webdav/TAV/Verification/SystemVerification/testdata/BCH'
-        Other options for production and test cases (respectively) are:
-          - '/srv/webdav/TAV/Verification/SystemVerification/testdata/TAV'
-          - '/srv/webdav/TAV/Verification/SystemVerification/testdata/TST'
+  -l : List the available source cases.
+  -k : Create .kill files for the copied simulations (with deliver=False).
+       The presence of these files will kill any running simulations with the
+       same names, without delivering their results (as this would overwrite
+       the copied results).
+  -d : Create .done files for the copied simulations. The presence of these
+       files notifies TAVIguide-web that the simulations have finished.
+  -t SRCTYPE : Specify the type of source case.
+       The default source case type is 'BCH' (benchmark cases)
+       Other options for the source case type are:
+         - 'TAV' (production cases)
+         - 'TST' (test cases)
+       See section 'Source cases' for more info.
+  -b BUMPDIR : Specify the path of the user's bumper directory.
+       The default bumper directory path is:
+         - '~/bumper'
+
+Source cases:
+
+  Source cases are located in subdirectories of 'feops1:/srv/webdav/TAV/
+  Verification/SystemVerification/testdata', depending on the type:
+    - 'BCH' for benchmark cases,
+    - 'TAV' for production cases and
+    - 'TST' for test cases.
+  If you want to change source cases or make new ones available for testing
+  purposes, this is where you do it.
 
 Examples:
 
-1. Listing the available benchmark cases in directory /home/user/benchmark:
+  1. Listing all production source cases:
 
-     $ $(basename $0) -lb /home/user/benchmark
+       $ $(basename $0) -lt TAV
 
-   This actually works by simply listing all files in the given directory, so
-   this does not necessarily only list valid benchmark cases.
+  2. Copying the CFD results of case TST000321 (which is an instance of
+     production source case TAV000123) to the user's bumper/results
+     directory and creating .done files in the user's bumper/requests
+     directory (DRY RUN):
 
-2. Copying the CFD results of benchmark case BCH00LT25 to the user's
-   bumper/results directory, renaming the copied files to case ID
-   TST000123 and creating .done files in the user's bumper/requests
-   directory:
-
-     $ $(basename $0) -ndc -r TST000123 BCH00LT25
+       $ $(basename $0) -ndt TAV cfd TAV000123 TST000321
   
-   Actually, the above command only simulates these actions. Remove the -n
-   option to really do it.
+  3. Typical copying of benchmark case simulation results during TAVIguide
+     testing will be done with the following task-specific commands:
 
-3. Typical copyback during TAVIguide testing will be done with the following
-   two commands, for FEA and CFD respectively:
-
-     $ $(basename $0) -dfr TESTID BENCHID
-     $ $(basename $0) -dcr TESTID BENCHID
+       FEA : $ $(basename $0) -kd fea BECHID TESTID
+       CFD : $ $(basename $0) -kd cfd BECHID TESTID
 
 EOF
 }
 
 
-get_fea_ids() {
-    local SIMID
-    local SIMIDS=
-    for SIMDIR in $BENCHSIMDIR/*; do
-	SIMID=$(basename $SIMDIR)
-	SIMIDS="$SIMIDS $SIMID"
-    done
-    echo "$SIMIDS"
-}
-
-
-copy_fea_results() {
-    local SIMID=$1
-    local SIMDIR=$BENCHSIMDIR/$SIMID
-    rsync $SIMDIR/ --include $SIMID'.*' --exclude '*'  $RESDIR/$SIMID -avhP $DRY
-}
-
-
-copy_cfd_results() {
-    local FEAID=$1
-    local CFDID=${FEAID}_cfd
-    local CFDRESDIR=${BENCHSIMDIR}/$FEAID/cfd/results
-    rsync $CFDRESDIR/ --include "PBBOX.pgf" --include "*.log" --exclude '*'  $RESDIR/$CFDID -avhP $DRY
-    for alignment in aligned misaligned; do
-	rsync $CFDRESDIR/ --include "${FEAID}_${alignment}*" --include "${FEAID}_${alignment}_logs/*" --exclude '*'  $RESDIR/$CFDID/${FEAID}_cfd_${alignment} -avhP $DRY
-    done
+element_not_in() {
+    # Test if element $1 is not in array ${@:2}.
+    local e
+    for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 1; done
+    return 0
 }
 
 
 rename_by_replace() {
-    # All files in directory $1 that have $2 in them are renamed by replacing $2 with $3.
+    # All files in directory $1 (and subdirectories) that have $2 in them are
+    # renamed by replacing $2 with $3.
     find $1 -depth -name "$2[.-]*" -exec rename $DRY "s|$2([^/]*)$|$3\$1|" {} \;
 }
 
 
 # Process the arguments.
-BENCHROOT=/srv/webdav/TAV/Verification/SystemVerification/testdata/BCH
 DRY=
-DONE=0
-LIST=0
-CFD=0
-FEA=0
-NEWID=
 ECHO=
+LIST=0
+KILL=0
+DONE=0
+SRCTYPE=BCH
+BUMPDIR=$HOME/bumper
 
 OPTIND=1 # Reset in case getopts has been used previously in the shell.
 
-while getopts "cdflnr:b:" opt; do
+while getopts "dklnt:b:" opt; do
     case "$opt" in
-        n)  DRY=-n
-	    ECHO='echo DRY RUN: '
-            ;;
-	d)  DONE=1
-	    ;;
-	c)  CFD=1
-	    ;;
-	f)  FEA=1
+	n)  DRY=-n
+	    ECHO="(DRY RUN) "
 	    ;;
 	l)  LIST=1
 	    ;;
- 	r)  NEWID=$OPTARG
+	k)  KILL=1
 	    ;;
-	b)  BENCHROOT=$OPTARG
+	d)  DONE=1
+	    ;;
+	t)  SRCTYPE=$OPTARG
+	    ;;
+	b)  BUMPDIR=$OPTARG
 	    ;;
     esac
 done
@@ -130,81 +114,105 @@ done
 shift $((OPTIND-1))
 
 # Set a few variables.
-BENCHIDS=$(ls $BENCHROOT)
+SRCCASESDIR=/srv/webdav/TAV/Verification/SystemVerification/testdata/$SRCTYPE
+SRCIDS=$(ls $SRCCASESDIR)
 [ "$LIST" = "1" ] && {
-    # If the -l option is used, only list available benchmark cases.
-    echo "The following benchmark cases are available in $BENCHROOT:"
-    for BENCHID in $BENCHIDS; do
-	echo "    $BENCHID"
+    # If the -l option is used, only list available source cases.
+    echo "The following source cases are available in '$SRCCASESDIR':"
+    for ID in $SRCIDS; do
+	echo "   $ID"
     done
     exit
 }
 
-BENCHID=$1
-[ -n "$BENCHID" ] || { usage; exit 111; }
-if [[ $BENCHIDS != *$BENCHID* ]]; then
-    echo "Benchmark case $BENCHID not available in $BENCHROOT."
-    echo "Use the -l option to list available benchmark cases."
+VALIDTASKS=("fea" "cfd")
+TASK=$1
+[ -n "$TASK" ] || { usage; exit 111; }
+if element_not_in "$TASK" "${VALIDTASKS[@]}"; then
+    echo "Task code '$TASK' is invalid. The following task codes are valid:"
+    echo "   ${VALIDTASKS[@]}"
     exit
 fi
 
-BENCHDIR=$BENCHROOT/$BENCHID
-BENCHSIMDIR=$BENCHDIR/simulations
-BENCHFEAIDS=$(get_fea_ids)
-RESDIR=$HOME/bumper/results
-REQDIR=$HOME/bumper/requests
+SRCIDS=($SRCIDS)
+SRCID=$2
+[ -n "$SRCID" ] || { usage; exit 111; }
+if element_not_in "$SRCID" "${SRCIDS[@]}"; then
+    echo "Source case '$SRCID' not available in '$SRCCASESDIR'."
+    echo "Use the -l option to list available source cases."
+    exit
+fi
 
-echo "Simulations for benchmark case $BENCHID:"
-for BENCHFEAID in $BENCHFEAIDS; do
-    echo "    $BENCHFEAID"
+TGTID=$3
+[ -n "$TGTID" ] || { usage; exit 111; }
+
+SRCCASEDIR=$SRCCASESDIR/$SRCID
+SRCSIMDIR=$SRCCASEDIR/simulations
+SRCSIMS=$(ls $SRCSIMDIR)
+echo "Simulations for source case '$SRCID':"
+for SRCSIM in $SRCSIMS; do
+    echo "   $SRCSIM"
 done
 
-[ "$FEA" = "1" ] && {
-    echo "Copying FEA results for benchmark case $BENCHID."
-    for BENCHFEAID in $BENCHFEAIDS; do
-	copy_fea_results $BENCHFEAID
+RESDIR=$BUMPDIR/results
+REQDIR=$BUMPDIR/requests
+
+# Copy files depending on selected task.
+[ "$TASK" = "fea" ] && {
+    echo "Copy source case's FEA simulation results."
+    TGTSIMS=
+    for SRCSIM in $SRCSIMS; do
+	TGTSIM="${SRCSIM//$SRCID/$TGTID}"
+	TGTSIMS="$TGTSIMS $TGTSIM"
+	if [ -d $RESDIR/$TGTSIM ]; then
+	    echo "Simulation results for '$TGTSIM' are already in '$RESDIR'!"
+	    echo "Aborting."
+	    exit
+	fi
+	rsync -avhP $SRCSIMDIR/$SRCSIM/* --include "$SRCSIM.*" --exclude "*"  $RESDIR/$TGTSIM $DRY
     done
-
-    [ -n "$NEWID" ] && {
-	# This cannot be taken outside, even if it's exactly the same code as for CFD,
-	# because the renaming has to happen before creating the done files.
-	echo "Renaming $BENCHID to $NEWID in $RESDIR."
-	rename_by_replace $RESDIR $BENCHID $NEWID
-    }
-
-    [ "$DONE" = "1" ] && {
-	NEWFEAIDS=$BENCHFEAIDS
-	[ -n "$NEWID" ] && NEWFEAIDS=${NEWFEAIDS//$BENCHID/$NEWID}
-	for NEWFEAID in $NEWFEAIDS; do
-	    echo "Creating .done file for $NEWFEAID."
-	    $ECHO touch $REQDIR/$NEWFEAID.done
-	done
-    }
 }
 
-[ "$CFD" = "1" ] && {
-    echo "Copying CFD results for benchmark case $BENCHID."
-    BENCHCFDIDS=
-    for BENCHFEAID in $BENCHFEAIDS; do
-	BENCHCFDIDS="$BENCHCFDIDS ${BENCHFEAID}_cfd"
-        copy_cfd_results $BENCHFEAID
-    done
-
-    [ -n "$NEWID" ] && {
-	# This cannot be taken outside, even if it's exactly the same code as for FEA,
-	# because the renaming has to happen before creating the done files.
-	echo "Renaming $BENCHID to $NEWID in $RESDIR"
-	rename_by_replace $RESDIR $BENCHID $NEWID
-    }
-
-    [ "$DONE" = "1" ] && {
-	NEWCFDIDS=$BENCHCFDIDS
-	[ -n "$NEWID" ] && NEWCFDIDS=${NEWCFDIDS//$BENCHID/$NEWID}
-	for NEWCFDID in $NEWCFDIDS; do
-	    echo "Creating .done files for $NEWCFDID."
-	    $ECHO touch $REQDIR/$NEWCFDID.done
+[ "$TASK" = "cfd" ] && {
+    echo "Copy source case's CFD simulation results."
+    TGTSIMS=
+    for SRCSIM in $SRCSIMS; do
+	TGTSIM="${SRCSIM//$SRCID/$TGTID}_cfd"
+	TGTSIMS="$TGTSIMS $TGTSIM"
+	if [ -d $RESDIR/$TGTSIM ]; then
+	    echo "Simulation results for '$TGTSIM' are already in '$RESDIR'!"
+	    echo "Aborting."
+	    exit
+	fi
+	rsync -avhP $SRCSIMDIR/$SRCSIM/cfd/results/* --include "PBBOX.pgf" --include "*.log" --exclude "*"  $RESDIR/$TGTSIM $DRY
+	for alignment in aligned misaligned; do
+	    rsync -avhP $SRCSIMDIR/$SRCSIM/cfd/results/* --include "${SRCSIM}_$alignment*" --include "${SRCSIM}_${alignment}_logs/*" --exclude "*" $RESDIR/$TGTSIM/${TGTSIM}_$alignment $DRY
 	done
-    }    
+    done
+}
+
+# Rename files in bumper results directory.
+echo "Rename '$SRCID' to '$TGTID' for files in '$RESDIR'."
+rename_by_replace $RESDIR $SRCID $TGTID
+
+# Create kill files for copied simulations (if requested).
+[ "$KILL" = "1" ] && {
+    for TGTSIM in $TGTSIMS; do
+	echo "$ECHO""Creating .kill file for simulation '$TGTSIM'."
+	[ "$DRY" = "" ] && {
+	    echo "deliver=False" > $REQDIR/$TGTSIM.kill
+	}
+    done
+}
+
+# Create done files for copied simulations (if requested).
+[ "$DONE" = "1" ] && {
+    for TGTSIM in $TGTSIMS; do
+	echo "$ECHO""Creating .done file for simulation '$TGTSIM'."
+	[ "$DRY" = "" ] && {
+	    touch $REQDIR/$TGTSIM.done
+	}
+    done
 }
 
 # End
